language: python
cache:
  - pip
  - npm
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- nightly
node_js:
  - "7"
git:
  depth: 3
notifications:
  email:
    on_success: never
install:
  - pip install -r requirements.txt
  - npm install -g firebase-tools --no-optional
script: python run.py build
after_success:
  - test ${TRAVIS_PYTHON_VERSION} = "3.6" && test ${TRAVIS_BRANCH} = "master" && test ${TRAVIS_PULL_REQUEST} = "false" && firebase deploy --token ${FIREBASE_TOKEN}
